name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  macos_tests:
    name: macOS Tests
    runs-on: 	macos-12
    strategy:
      fail-fast: false
      matrix: 
        xcode: ["13.4", "13.3.1"]

    steps:
    - uses: actions/checkout@v3

    - name: Select Xcode ${{ matrix.xcode }}
      run: sudo xcode-select --switch /Applications/Xcode_${{ matrix.xcode }}.app
    
    - name: make test
      run: make test